### ISSUE TITLE
[BUG] Failure with nltk download sometimes due to utils_nlp/dataset/__init__.py

### ISSUE THREAD

**Issue by janhavi13** [microsoft/nlp-recipes#257]
This file - https://github.com/microsoft/nlp/blob/master/utils_nlp/dataset/__init__.py causes failure on Azure cluster with `File exists error` when a previous run on an nc24 gpu cluster is cancelled and a new run is started I usually get this error. I'm wondering if we should handle this since a user might likely do this if he/she wants to change configs in the notebook immediately rather than waiting for entire run to complete.

### How do we replicate the bug?
Run the entailment_xnli_bert_azureml notebook on nc24 with 2 nodes. 
**Expected behavior** :
The experiment failed. Finalizing run...
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from utils_nlp.dataset.xnli_torch_dataset import XnliDataset
  File "/mnt/batch/tasks/shared/LS_root/jobs/maidaipbert-eastus/azureml/nlp-entailment-bert_1565318473_b939a491/mounts/workspaceblobstore/azureml/NLP-Entailment-BERT_1565318473_b939a491/utils_nlp/dataset/__init__.py", line 8, in <module>
    nltk.download("stopwords", quiet=True)
  File "/azureml-envs/azureml_462b384392302935cd8ea420bcf8170e/lib/python3.6/site-packages/nltk/downloader.py", line 670, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/azureml-envs/azureml_462b384392302935cd8ea420bcf8170e/lib/python3.6/site-packages/nltk/downloader.py", line 555, in incr_download
    for msg in self._download_package(info, download_dir, force):
  File "/azureml-envs/azureml_462b384392302935cd8ea420bcf8170e/lib/python3.6/site-packages/nltk/downloader.py", line 612, in _download_package
    os.mkdir(os.path.join(download_dir, info.subdir))
FileExistsError: [Errno 17] File exists: '/root/nltk_data/corpora'

**Comment by daden-ms** [comment]
issue no longer exists in the current staging.
